### PR TITLE
Adding additional option to manage several schemas

### PR DESCRIPTION
**Pull request by Integritus**
Hi @crossroad0201 ! 
Sorry to bother you again, I need another PR for this, this time I'm adding another option to select the schemas that flyway should manage. I'm not very proficient in Scala, so I'm not completely sure if I am split the schemas string correctly or if the class for schema has the proper type on it's constructor, I do know that the setSchemas should accept a String array. Let me know if I'm doing something wrong and I hope this can be merged soon. Thanks!

### CODE REVIEW

**Comment by crossroad0201** [comment]
Thank you @Integritus.
I think the code is OK :-)

**Comment by crossroad0201** [comment]
Mm... compile error...
I fix it. Please wait...

**Comment by crossroad0201** [comment]
Fixed it, and released.
To apply arrays to variable arity method, had to expand them using `_: *` syntax.

**Comment by Integritus** [comment]
Thanks!

**Pull request merged**
